name: Pull Request Test

on:
    pull_request:
#      PR이 열렸을때, 동기화 되었을때, PR이 다시 열렸을때
      types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.2
      - name: JDK install
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '17'
          cache: 'gradle'

      - name: Gradle Build
        run: |
          ./gradlew build --parallel
